#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cpu-temp"
name = "CPU Temperature"
description.en = "Display the current CPU temperature of your server."
description.fr = "Affiche la température actuelle du processeur de votre serveur."

version = "1.0~ynh1"

maintainers = ["yourusername"]

[upstream]
license = "MIT"
website = "https://github.com/yourusername/cpu-temp"
demo = "https://yourwebsite.com/cpu-temp-demo"  # Optional, if you have a demo site
admindoc = "https://github.com/yourusername/cpu-temp/blob/main/README.md"
userdoc = "https://github.com/yourusername/cpu-temp/blob/main/README.md"
code = "https://github.com/yourusername/cpu-temp"
cpe = "cpe:2.3:a:cpu-temp:cpu-temp"  # Optional: CPE for security tracking

# Optional: Funding link (if applicable)
fund = "https://yourfundingurl.com"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false  # This app does not need multiple instances

# LDAP and SSO settings for login (not relevant for this app)
ldap = "not_relevant"
sso = "not_relevant"

# Estimations for disk and RAM usage
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/cpu-temp"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Leave blank if no password is required."
    help.fr = "Laissez vide si aucun mot de passe n'est requis."
    type = "password"

[resources]
    # App source and resources configuration

    [resources.sources]
        [resources.sources.main]
        # Replace with the actual URL of your app release
        url = "https://github.com/yourusername/cpu-temp/archive/refs/tags/v1.0.0.tar.gz"
        sha256 = "insert_sha256_hash_here"  # Replace with the actual SHA256 hash of the source file

    [resources.system_user]
        # Define a system user if needed (not required in this case)

    [resources.install_dir]
        type = "install_dir"
        default = "/var/www/cpu-temp"

    [resources.data_dir]
        type = "data_dir"
        default = "/home/yunohost.app/cpu-temp"

    [resources.permissions]
        # Configure access permissions for your app (public in this case)
        main.url = "/cpu_temp"

    [resources.ports]
        # YunoHost will automatically assign a port for reverse-proxying

    [resources.apt]
        # The required system package for the app
        packages = "lm-sensors"

    [resources.database]
        # If your app uses a database, configure it here (not needed for this app)
